version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    ports:
      - "8889:8889"
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver2
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./dist:/var/www/html/dist
      - ./index.html:/var/www/html/index.html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
